name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  APP_KEYS: TRlbMBSMOZ1TQV5CevOjAA==,x3nHmUiDhib8NeTtDDanjg==,/HeZIEYgTN4XhClU7E7pgA==,3II6NqXxNq3Av0X2xkYH6Q==
  API_TOKEN_SALT: OIVz+gPSkAWc6aqBh+sW7A==
  ADMIN_JWT_SECRET: xVp1ubf+HHc+JZVQ+m9NEA==
  TRANSFER_TOKEN_SALT: OCkd7KJ6zU2K4RpEaCQA4A==

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build Next.js project
        run: npm run test
        working-directory: ./backend

